services:
  - type: web
    name: java-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/Learner-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DB_URL
        value: jdbc:mysql://43Xd1KYxuk6jth6.root:699VwL2ISPzKddIp@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&verifyServerCertificate=false
      - key: DB_USERNAME
        value: 43Xd1KYxuk6jth6.root
      - key: DB_PASSWORD
        value: 699VwL2ISPzKddIp
